ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "usn" TEXT,
ADD COLUMN IF NOT EXISTS "degree" TEXT,
ADD COLUMN IF NOT EXISTS "branch" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "User_usn_key" ON "User"("usn");
