export const categories = [
  "Electronics",
  "Books",
  "Furniture",
  "Clothing",
  "Sports",
  "Bikes",
  "Notes & Study Material",
  "Other",
] as const;

export const landingMockListings = [
  {
    id: "1",
    title: "MacBook Air 13-inch",
    description: "Lightweight MacBook Air in great working condition, ideal for lectures, projects, and everyday campus use.",
    price: 48000,
    category: "Electronics",
    condition: "Good",
    location: "North Quad",
    imageUrls: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80"],
    createdAt: "2026-10-04T12:00:00.000Z",
    seller: {
      name: "Ananya Rao",
      email: "ananya.rao@campus.edu",
      usn: "NB25ISE111",
      degree: "BE",
      branch: "Information Science and Engineering",
    },
  },
  {
    id: "2",
    title: "Chemistry Lab Kit",
    description: "Complete chemistry lab kit with the essentials for practical sessions. A convenient option for students starting the course.",
    price: 1200,
    category: "Books",
    condition: "Like New",
    location: "Engineering Hall",
    imageUrls: ["https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80"],
    createdAt: "2026-10-07T12:00:00.000Z",
    seller: {
      name: "Arjun Nair",
      email: "arjun.nair@campus.edu",
      usn: "NB24CSE208",
      degree: "BTech",
      branch: "Computer Science and Engineering",
    },
  },
  {
    id: "3",
    title: "Ergonomic Study Chair",
    description: "Comfortable ergonomic chair for long study sessions, with supportive cushioning and an adjustable height.",
    price: 4500,
    category: "Furniture",
    condition: "Good",
    location: "West Residence",
    imageUrls: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80"],
    createdAt: "2026-09-24T12:00:00.000Z",
    seller: {
      name: "Kavya Reddy",
      email: "kavya.reddy@campus.edu",
      usn: "NB25ECE054",
      degree: "BE",
      branch: "Electronics and Communication Engineering",
    },
  },
  {
    id: "4",
    title: "Hybrid Campus Bicycle",
    description: "Reliable hybrid bike with a lightweight frame and smooth gears, ready for daily campus commutes.",
    price: 12000,
    category: "Bikes",
    condition: "Good",
    location: "East Campus",
    imageUrls: ["https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=80"],
    createdAt: "2026-10-05T12:00:00.000Z",
    seller: {
      name: "Rohan Shetty",
      email: "rohan.shetty@campus.edu",
      usn: "NB24ME103",
      degree: "BE",
      branch: "Mechanical Engineering",
    },
  },
  {
    id: "5",
    title: "Campus Club Hoodie",
    description: "Soft, comfortable college hoodie in very good condition. Great for everyday wear around campus.",
    price: 800,
    category: "Clothing",
    condition: "Like New",
    location: "Student Centre",
    imageUrls: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=1200&q=80"],
    createdAt: "2026-10-06T12:00:00.000Z",
    seller: {
      name: "Meera Iyer",
      email: "meera.iyer@campus.edu",
      usn: "NB25CIV077",
      degree: "BTech",
      branch: "Civil Engineering",
    },
  },
  {
    id: "6",
    title: "Badminton Racket Set",
    description: "Pair of lightweight badminton rackets with a few shuttlecocks, ideal for games between classes.",
    price: 1600,
    category: "Sports",
    condition: "Good",
    location: "Sports Complex",
    imageUrls: ["https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=80"],
    createdAt: "2026-10-02T12:00:00.000Z",
    seller: {
      name: "Vikram Rao",
      email: "vikram.rao@campus.edu",
      usn: "NB24EEE061",
      degree: "BE",
      branch: "Electrical and Electronics Engineering",
    },
  },
  {
    id: "7",
    title: "First-Year Engineering Notes",
    description: "Organized handwritten notes and revision sheets for core first-year engineering subjects.",
    price: 350,
    category: "Notes & Study Material",
    condition: "Good",
    location: "Central Library",
    imageUrls: ["https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80"],
    createdAt: "2026-10-01T12:00:00.000Z",
    seller: {
      name: "Diya Kulkarni",
      email: "diya.kulkarni@campus.edu",
      usn: "NB25AIM019",
      degree: "BTech",
      branch: "Artificial Intelligence and Machine Learning",
    },
  },
  {
    id: "8",
    title: "Desk Organizer Set",
    description: "A handy set of desk organizers to keep stationery, cables, and study essentials in order.",
    price: 500,
    category: "Other",
    condition: "Like New",
    location: "Library Annex",
    imageUrls: ["https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=80"],
    createdAt: "2026-10-08T10:00:00.000Z",
    seller: {
      name: "Nikhil Bhat",
      email: "nikhil.bhat@campus.edu",
      usn: "NB24DSC132",
      degree: "BE",
      branch: "Data Science",
    },
  },
];
